### GET ALL USERS
GET https://localhost:5001/users/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJvbWFyQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJHpkaS5kSzJOLmdKdTlsS1dRcTZPRy5qSWd2TWJQekVvL2xtZkIzUVlpdS93WERrMDdUbjJ1Iiwicm9sZV9pZCI6MSwicGhvbmUiOjEyMzQ1Njc4OTAsImlhdCI6MTcyNzEzMTI5NiwiZXhwIjoxNzI3MTM0ODk2fQ.ERfCFJhl5Kxf8SpJzFaUnV2xAnBh-FUKuKeqAHXOIE4


### POST NEW USER
POST https://localhost:5001/users/register
Content-Type: application/json

{
    "name": "Zumaya",
    "email": "zumaya@gmail.com",
    "password": "hola",
    "role_id": 1,
    "phone": "5577889966"
}

### LOGIN USER
POST https://localhost:5001/users/login
Content-Type: application/json

{
    "email": "omar@gmail.com",
    "password": "123456"
}

### Register donation
POST https://localhost:5001/users/registerDonation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJvbWFyQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJHpkaS5kSzJOLmdKdTlsS1dRcTZPRy5qSWd2TWJQekVvL2xtZkIzUVlpdS93WERrMDdUbjJ1Iiwicm9sZV9pZCI6MSwicGhvbmUiOjEyMzQ1Njc4OTAsImlhdCI6MTcyNzEzMTI5NiwiZXhwIjoxNzI3MTM0ODk2fQ.ERfCFJhl5Kxf8SpJzFaUnV2xAnBh-FUKuKeqAHXOIE4

{
    "amount": 45000,
    "donor_id": 3,
    "type_id": 2,
    "comment": "From web",
    "sector_id": 2
}